[features]
seeds = false
skip-lint = false
[programs.localnet]
starnft = "BBw4HBNzXwRA6HJpdbLFeaBqwuAqRSjiRYVGavH3vSqV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/arieotech/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
